apiVersion: v1
kind: Service
metadata:
  name: no-waste-product-manager-service
spec:
  type: LoadBalancer
  ports:
    - port: 8103
      targetPort: 8003
      protocol: TCP
      name: http
  selector:
    app: no-waste-product-manager