apiVersion: v1
kind: Service
metadata:
  name: products-redis-service
spec:
  type: LoadBalancer
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: http
  selector:
    app: products-redis