apiVersion: v1
kind: Service
metadata:
  name: no-waste-test-service-service
spec:
  type: LoadBalancer
  ports:
    - port: 8100
      targetPort: 8200
      protocol: TCP
      name: http
  selector:
    app: no-waste-test-service