apiVersion: apps/v1
kind: Deployment
metadata:
  name: no-waste-test-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: no-waste-test-service
  template:
    metadata:
      labels:
        app: no-waste-test-service
    spec:
      containers:
        - name: no-waste-test-service-pod
          image: com.github.kissbudai/no-waste-test-service-img
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8100
