apiVersion: v1
kind: Service
metadata:
  name: no-waste-auth-manager-service
spec:
  type: LoadBalancer
  ports:
    - port: 8101
      targetPort: 8001
      protocol: TCP
      name: http
  selector:
    app: no-waste-auth-manager