apiVersion: v1
kind: Service
metadata:
  name: no-waste-request-manager-service
spec:
  type: LoadBalancer
  ports:
    - port: 8104
      targetPort: 8004
      protocol: TCP
      name: http
  selector:
    app: no-waste-request-manager