apiVersion: v1
kind: Service
metadata:
  name: no-waste-proxy-service
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8762
      protocol: TCP
      name: http
  selector:
    app: no-waste-proxy