apiVersion: v1
kind: Service
metadata:
  name: no-waste-eureka-service
spec:
  type: LoadBalancer
  ports:
    - port: 8761
      targetPort: 8761
      protocol: TCP
      name: http
  selector:
    app: no-waste-eureka