apiVersion: v1
kind: Service
metadata:
  name: no-waste-user-manager-service
spec:
  type: LoadBalancer
  ports:
    - port: 8102
      targetPort: 8002
      protocol: TCP
      name: http
  selector:
    app: no-waste-user-manager